### ISSUE TITLE
Get a basic structure for subcommands/argument parsing setup

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#104]
This will open up the project to more easily be worked on by multiple people at once. And get some real code in the project :)

We're going to use [clap-rs](https://github.com/kbknapp/clap-rs).

**Comment by reillysiemens** [comment]
Specifically we're going to try to use the `clap_app!` macro style.

**Comment by RadicalZephyr** [comment]
Current list of initial subcommands: `init`, `clone`, `use`, `add`, `status`, `doctor`, `git`
