### ISSUE TITLE
Implement link utility

### ISSUE THREAD

**Issue by reillysiemens** [bike-barn/hermit#116]

**Comment by reillysiemens** [comment]
This should belong to a `utils` module.

**Comment by RadicalZephyr** [comment]
Plans have changed here.  We now have a `FileOperations` struct which allows us to decomplect the code that has _intent_ to change the filesystem, from actually changing the filesystem.  The `link` utility should make use of this, but it still has distinct behavior (i.e. traversing a shell and setting up all the correct symlinks).
