### ISSUE TITLE
Implement unlink utility

### ISSUE THREAD

**Issue by reillysiemens** [bike-barn/hermit#117]

**Comment by reillysiemens** [comment]
This should belong to a `utils` module.

**Comment by RadicalZephyr** [comment]
Plans have changed here. We now have a FileOperations struct which allows us to decomplect the code that has intent to change the filesystem, from actually changing the filesystem. The unlink utility should make use of this, but it still has distinct behavior (i.e. traversing a home directory and removing all the correct symlinks).
