### ISSUE TITLE
Implement the rest of the planned subcommands

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#12]
- [x] init   - Create a new profile
- [x] add    - Add a file/folder to the profile
- [x] ~~redact~~ add -r - Add a file with sensitive information, do complicated
  stuff to make it safe(r)
- [x] status - Currently, just does `git status` in the profile dir,
  should give info about other stuff like what files haven't been linked
- [x] git  - Run arbitrary git commands in the profile dir
- [ ] open   - Move user into the profile dir for down and dirty work
- [x] link   - Generate symlinks for all files in your attache dir
  into home
- [x] unlink - Remove all the symlinks for the current profile
- [x] clone  - Get a remote git repository and set it up as the
  contents of your attache dir
- [x] use    - Switch to using a particular profile (use unlink and link) (works-ish, pending completion of unlink)
- [x] update - Update one (or possibly all?) files in a repository (see #44)
- [x] doctor - Make sure that your hermit is in a sane state
- [x] upgrade - Upgrade the user to the latest released version of hermit

[6cfa1d5]: https://github.com/RadicalZephyr/hermit/commit/6cfa1d5b27e7fab24fa8e8a24a9d759ff6ec81cea

**Comment by reillysiemens** [comment]
What is `hermit doctor` supposed to do that `hermit status` doesn't?

**Comment by RadicalZephyr** [comment]
https://github.com/RadicalZephyr/hermit/issues/16

**Comment by reillysiemens** [comment]
Got it. `hermit doctor` is basically `hermit sanity`.

**Comment by RadicalZephyr** [comment]
closing in favor of issues per subcommand.
