### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by polyzen** [bike-barn/hermit#166]
A checkout of master fails with a common issue: https://ptpb.pw/ECjo

Hermit builds and the checks pass after a `cargo update`, but I haven't yet begun using and properly testing it out.

It seems you are busy elsewhere, but I would just like to mention [Dependabot](https://dependabot.com/) has become quite popular for keeping on top of dependency updates.

**Comment by RadicalZephyr** [comment]
Thanks for the tip! Dependabot looks very useful.
