### ISSUE TITLE
Add checking for our binary dependencies on installation

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#36]
This dovetail's with @reillysiemens adding of a list of our dependencies.

**Comment by reillysiemens** [comment]
Maybe this is part of `hermit doctor`?

**Comment by RadicalZephyr** [comment]
yes, yes it is.

**Comment by reillysiemens** [comment]
We won't have the same kind of binary dependencies on installation after we migrate to Rust. I think we can safely close this issue with the knowledge that we'll need to do a different sort of dependency checking later on.
