### ISSUE TITLE
Deal with test inefficiencies...

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#62]
As more tests get added, the tests are running slower. The order of growth seems to be ~1+ second per test.  Which isn't really going to cut it long term.  We're already up to 22 seconds per test run.  And to test using multiple profiles I'm using the hack of running the whole test suite again!! So full test time is up to a minute already. Not a good trend.

Two things to consider.  Possibly urchin is sort of slow.  Or! the way we are writing our tests is slow. Or most problematic of all, it could be that what hermit does is so disk intensive that it is going to _inevitably_ be slow to test.  Especially with proper cleanups.

**Comment by reillysiemens** [comment]
Urchin is slow, but `cargo` tries to run tests in parallel. This doesn't seem like a particularly relevant issue anymore in light of the switch to Rust.
