### ISSUE TITLE
Figure out what to do when patch fails

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#63]
When we are propagating changes made to a redacted file, there is a very real chance that the reverse patching will just fail.  The question is, how do we deal with it?  Right now, with `set -e` on, hermit will just quit, leaving a reject file there.

I don't think that this is ideal though.  Really, being able to leverage the way git handles merge conflicts would probably be best.  Print a message and modify the file so it's obvious where the diffs were.

**Comment by reillysiemens** [comment]
I don't know that we'll be using `patch` directly like this in the switch to Rust. I'd say we can close this one and address the issue if it crops up again in a different way.
