### ISSUE TITLE
Add examples to the documentation pages

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#65]
Pretty self-explanatory.

**Comment by reillysiemens** [comment]
Do you want to enumerate all possible options or just some key ones to get people interested?

**Comment by RadicalZephyr** [comment]
Good question.  Probably start out with key examples.  But ideally it would be sort of a reference style set of examples where you can use it to find out how to do that thing you need to do right now.  I also want to start a tutorial like Leiningen has.  Like a comprehensive walkthrough of how to start using hermit effectively once you have it installed.

**Comment by reillysiemens** [comment]
Is [this](https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md) the tutorial you're talking about? That seems like a really good idea. I'm in. Is there a Trello for this project?

**Comment by reillysiemens** [comment]
Ah. I see now that #66 is a thing.

**Comment by RadicalZephyr** [comment]
There is no Trello as yet.  Not enough people working on it to warrant one. :wink: @reillysiemens :wink:

**Comment by reillysiemens** [comment]
There is now https://waffle.io/bike-barn/hermit. I think #66 should really handle this, so I think we can safely close this and let that become its successor.
