### ISSUE TITLE
Address the "removing a profile" use case.

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#72]
As described in #67 there's erroneous behavior when it's done manually.  The only barrier I see to adding a `remove` command is that it might sound like a thing you do to files to remove them from a profile.  Maybe profile's should have their own sub-sub-commands? I can envision the desire to rename profiles as well...

**Comment by RadicalZephyr** [comment]
Or as suggested in slack we could call it `hermit nuke`

**Comment by houngj** [comment]
Would it be good to just init/use the default profile if you were to nuke the profile currently being used?

**Comment by RadicalZephyr** [comment]
Good question.  I'm not 100% sure.  I think that might be sort of surprising behaviour though.  I think more generally we need to decide whether being in a state where no profile is active is valid or not.

Another solution (that I like better than a silent `init` or `use`) is to make it so that you can't `nuke` the profile you currently have activated.  But this kind of makes it weird, because if the profile isn't active then we don't need a nuke command, you could just `rm-rf` it and everything would be fine...

**Comment by RadicalZephyr** [comment]
Overall, I think that hermit *has* to be able to gracefully deal with the situation of not having an activated profile, and we have to be able to clean up symbolic links without relying on the profile being there.

**Comment by houngj** [comment]
Maybe we should just a have a reserved keyword for the current parameter in .git? So if we were to delete a profile that is being used we can `set-current-profile 'none'` so that we can just check for the keyword none in the scripts. Of course this means that users wont be able to create a profile with that keyword.

**Comment by RadicalZephyr** [comment]
I guess I don't really see how that addresses the problem.  That will work fine as long as the user always uses `nuke` to delete their profile, but then so would just setting the key to the empty string.  The thing is though I don't think that's something we can count on. Humans are notoriously unreliable ;)

**Comment by houngj** [comment]
oh right.. yeah an empty string would work well as a key. I was just addressing the problem of deleting a currently used profile properly with `nuke`.

**Comment by reillysiemens** [comment]
My opinion is that you should totally be able to be in a state where you aren't currently using a profile. At those times hermit subcommands dealing with profiles should gracefully fail with something like
> "Sorry, you aren't using a profile right now. Run `hermit init` or `hermit clone` to create a new profile."

I think it's fair to require that `hermit nuke` always have the profile name as an argument and that we throw a warning up in yellow/red asking if they really want to delete the profile.

Provided they **really** do want to delete the profile it should remove all the profile symlinks and `rm -rf` the profile.

**Comment by RadicalZephyr** [comment]
That sounds eminently reasonable.  It's actually just an extension of what we do know for an empty hermit profile key.  I think the only thing that needs to change is the `check-profile` helper. Maybe not even that...

**Comment by reillysiemens** [comment]
The origin of this issue is probably a `bash` error, but I think the functionality will still be relevant in the switch to Rust, so let's keep this issue open until we address it in Rust.

**Comment by RadicalZephyr** [comment]
Closing, see #110 for the current tracking on this issue.
