### ISSUE TITLE
Make the hermit dispatcher a shell function

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#80]
In preparation for adding the `open` command that will `pushd` you into your hermit profile dir so you can run git commands directly.

**Comment by reillysiemens** [comment]
Unless I'm mistaken there shouldn't be _any_ shell functions once we switch to Rust, so I think we can close this one.

**Comment by reillysiemens** [comment]
Unless I'm mistaken there shouldn't be _any_ shell functions once we switch to Rust, so I think we can close this one.
