### ISSUE TITLE
hermit status reports a different profile than the one files are symlinked from after a hermit clone

### ISSUE THREAD

**Issue by reillysiemens** [bike-barn/hermit#89]
While using the `default` profile I did a `hermit clone` of another profile. `hermit status` now reports that my new profile is being used, but the symlinked files are still listed as belonging to the `default` profile.

**Comment by RadicalZephyr** [comment]
Clone must have the same problem that use had.  There is something really gnarly about the way we are handling the `HERMIT_PROFILE` variable...

**Comment by reillysiemens** [comment]
I think this `HERMIT_PROFILE` handling is probably due to a `bash` issue and won't be relevant anymore in a Rust implementation.
