### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by houngj** [bike-barn/hermit#96]
Travis tests are breaking due to a changes in their virtualization infrastructure.

**Comment by reillysiemens** [comment]
This is already fixed by #95.

**Comment by reillysiemens** [comment]
Well, not quite. Travis will still need fixing after that to bring it in line with Rust tests.

**Comment by houngj** [comment]
For now Travis will be running the bash tests and then later on they will be replaced with Rust tests.
