### ISSUE TITLE
Consider detailing labels in CONTRIBUTING.md.

### ISSUE THREAD

**Issue by reillysiemens** [bike-barn/hermit#99]
I currently have no idea what the `ready` label is for. We might help newcomers by explaining our current usage of labels in `CONTRIBUTING.md`.

**Comment by RadicalZephyr** [comment]
I think the labels we're using are pretty self-explanatory now that we use `to-do` instead of `ready`.  Also, I don't think anyone can add/change labels except repository owners.

**Comment by reillysiemens** [comment]
This is a fair point. I also think things make a lot more sense if we just point them to waffle.io somewhere.
